version: '3.6'

services:
  app-service:
    build: ./services/app
    ports:
      - '4001:4001'
    volumes:
      - ./services/app:/usr/local/app
  user-service:
    build: ./services/user
    ports:
      - '4002:4002'
    volumes:
      - ./services/user:/usr/local/user
